title: MauricioStradaPhotography.com
description: >
  Fotógrafo profesional de bodas, comuniones, books, estudio, reportajes,
  fotografía erótica, publicidad, de producto y alimentación.
url: https://mauriciostradaphotography.com
email: mauriciostradaphotography@gmail.com
lang: es

phone:
  es: "+34 643 85 18 84"
  ch: "+41 779448470"

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - scripts
  - assets/images/visitas-source

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      path: "galerias"
      type: pages
    values:
      layout: gallery
      body_class: page-gallery
      scripts:
        - lazy-images
        - gallery

  - scope:
      path: "galerias/videos-externos"
      type: pages
    values:
      scripts:
        - lazy-images
        - video-gallery
